version: "3.8"

services:
  nginx:
    image: nginx:${TAG}
    env_file:
      - ./.env # By default it uses .env but this value is set to specify that .env file is used for config.
    read_only: false
    ports:
      - "80:80"
    volumes:
      - ${HTML_MOUNT_PATH}:/usr/share/nginx/html
      - ${CONFIG_MOUNT_PATH}:/etc/nginx/conf.d
      - ${SSL_MOUNT_PATH}:/etc/nginx/ssl

